-- 商户信息管理功能测试数据
-- 在已有的测试数据基础上，创建一个测试商户和对应的账号

-- 1. 创建一个测试商户
INSERT INTO STORE (STORE_ID, STORE_NAME, STORE_STATUS, STORE_TYPE, TENANT_NAME, CONTACT_INFO, RENT_START, RENT_END) 
VALUES (1, '测试咖啡店', '正常营业', '个人', '张三', '13800138000', DATE '2024-01-01', DATE '2025-12-31');

-- 2. 创建对应的商户账号
INSERT INTO ACCOUNT (ACCOUNT, PASSWORD, IDENTITY, USERNAME, AUTHORITY) 
VALUES ('store_000001', 'store123', '商户', '张三', 4);

-- 3. 建立店铺和账号的关联
INSERT INTO STORE_ACCOUNT (ACCOUNT, STORE_ID) 
VALUES ('store_000001', 1);

-- 4. 建立店铺和区域的租用关系
INSERT INTO RENT_STORE (STORE_ID, AREA_ID) 
VALUES (1, 1);

-- 5. 更新区域状态为已租用
UPDATE AREA SET ISEMPTY = 0, CATEGORY = 'RETAIL' WHERE AREA_ID = 1;
UPDATE RETAIL_AREA SET RENT_STATUS = '已租用' WHERE AREA_ID = 1;

COMMIT;

-- 验证数据
SELECT '商户信息' as "类型", s.STORE_ID, s.STORE_NAME, s.STORE_STATUS, s.TENANT_NAME, s.CONTACT_INFO
FROM STORE s;

SELECT '商户账号' as "类型", a.ACCOUNT, a.USERNAME, a.IDENTITY, a.AUTHORITY
FROM ACCOUNT a
WHERE a.IDENTITY = '商户';

SELECT '账号关联' as "类型", sa.ACCOUNT, sa.STORE_ID, s.STORE_NAME
FROM STORE_ACCOUNT sa
JOIN STORE s ON sa.STORE_ID = s.STORE_ID;

SELECT '租用关系' as "类型", rs.STORE_ID, rs.AREA_ID, ra.RENT_STATUS
FROM RENT_STORE rs
JOIN RETAIL_AREA ra ON rs.AREA_ID = ra.AREA_ID;
