-- Oracle 数据库测试数据初始化脚本（正确版本）
-- 基于实际的表结构：AREA -> RETAIL_AREA 继承关系

-- 清理可能存在的测试数据
DELETE FROM RENT_STORE WHERE AREA_ID IN (1,2,3,4);
DELETE FROM STORE_ACCOUNT WHERE STORE_ID IN (SELECT STORE_ID FROM STORE WHERE STORE_NAME LIKE '测试%');
DELETE FROM STORE WHERE STORE_NAME LIKE '测试%';
DELETE FROM RETAIL_AREA WHERE AREA_ID IN (1,2,3,4);
DELETE FROM AREA WHERE AREA_ID IN (1,2,3,4);
DELETE FROM ACCOUNT WHERE ACCOUNT = 'admin_test';

-- 1. 先插入基础区域表 AREA
INSERT INTO AREA (AREA_ID, ISEMPTY, AREA_SIZE, CATEGORY) 
VALUES (1, 1, 50, 'RETAIL');  -- 空置，50平米

INSERT INTO AREA (AREA_ID, ISEMPTY, AREA_SIZE, CATEGORY) 
VALUES (2, 1, 80, 'RETAIL');  -- 空置，80平米

INSERT INTO AREA (AREA_ID, ISEMPTY, AREA_SIZE, CATEGORY) 
VALUES (3, 1, 120, 'EVENT'); -- 空置，120平米

INSERT INTO AREA (AREA_ID, ISEMPTY, AREA_SIZE, CATEGORY) 
VALUES (4, 0, 60, 'OTHER');  -- 已占用，60平米

-- 2. 再插入零售区域表 RETAIL_AREA（继承自AREA）
INSERT INTO RETAIL_AREA (AREA_ID, RENT_STATUS, BASE_RENT) 
VALUES (1, '空置', 5000.00);

INSERT INTO RETAIL_AREA (AREA_ID, RENT_STATUS, BASE_RENT) 
VALUES (2, '空置', 8000.00);

INSERT INTO RETAIL_AREA (AREA_ID, RENT_STATUS, BASE_RENT) 
VALUES (3, '空置', 12000.00);

INSERT INTO RETAIL_AREA (AREA_ID, RENT_STATUS, BASE_RENT) 
VALUES (4, '已租用', 6000.00);

-- 3. 插入测试管理员账号
INSERT INTO ACCOUNT (ACCOUNT, PASSWORD, IDENTITY, USERNAME, AUTHORITY) 
VALUES ('admin_test', 'admin123', '员工', '测试管理员', 1);

-- 提交更改
COMMIT;

-- 4. 验证查询 - 使用JOIN查询完整信息
SELECT a.AREA_ID, a.AREA_SIZE, a.ISEMPTY, a.CATEGORY, ra.RENT_STATUS, ra.BASE_RENT
FROM AREA a
JOIN RETAIL_AREA ra ON a.AREA_ID = ra.AREA_ID
WHERE a.ISEMPTY = 1 AND ra.RENT_STATUS = '空置';

-- 查看账号
SELECT ACCOUNT, USERNAME, IDENTITY, AUTHORITY 
FROM ACCOUNT 
WHERE ACCOUNT = 'admin_test';

-- 查看所有测试数据
SELECT '区域总数' as "统计", COUNT(*) as "数量" FROM AREA WHERE AREA_ID IN (1,2,3,4)
UNION ALL
SELECT '零售区域总数', COUNT(*) FROM RETAIL_AREA WHERE AREA_ID IN (1,2,3,4)
UNION ALL
SELECT '空置区域数', COUNT(*) FROM AREA WHERE AREA_ID IN (1,2,3,4) AND ISEMPTY = 1
UNION ALL
SELECT '管理员账号数', COUNT(*) FROM ACCOUNT WHERE ACCOUNT = 'admin_test';