--------------------------------------------------------
--  文件已创建 - 星期四-九月-11-2025   
--------------------------------------------------------

-- 切换当前会话的容器
ALTER SESSION SET CONTAINER = XEPDB1;

-- 创建用户 (替换为你自己的密码)
CREATE USER ORACLEDBA IDENTIFIED BY "23OracleServer";

-- 授权
GRANT CONNECT, RESOURCE TO ORACLEDBA;
GRANT UNLIMITED TABLESPACE TO ORACLEDBA;

-- 切换用户（建表）
ALTER SESSION SET CURRENT_SCHEMA = ORACLEDBA;

--------------------------------------------------------
--  DDL for Sequence COLLABORATION_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "COLLABORATION_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence EVENT_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "EVENT_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence STAFF_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "STAFF_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table ACCOUNT
--------------------------------------------------------

  CREATE TABLE "ACCOUNT" 
   (	"ACCOUNT" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(50 BYTE), 
	"IDENTITY" VARCHAR2(20 BYTE), 
	"USERNAME" VARCHAR2(50 BYTE), 
	"AUTHORITY" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "ACCOUNT"."ACCOUNT" IS '账号';
   COMMENT ON COLUMN "ACCOUNT"."PASSWORD" IS '密码';
   COMMENT ON COLUMN "ACCOUNT"."IDENTITY" IS '身份(商户/员工)';
   COMMENT ON COLUMN "ACCOUNT"."USERNAME" IS '用户名';
   COMMENT ON COLUMN "ACCOUNT"."AUTHORITY" IS '权限';
--------------------------------------------------------
--  DDL for Table AREA
--------------------------------------------------------

  CREATE TABLE "AREA" 
   (	"AREA_ID" NUMBER(*,0), 
	"ISEMPTY" NUMBER(*,0) DEFAULT 1, 
	"AREA_SIZE" NUMBER(*,0), 
	"CATEGORY" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "AREA"."AREA_ID" IS '区域ID';
   COMMENT ON COLUMN "AREA"."ISEMPTY" IS '是否空置，0-否，1-是';
   COMMENT ON COLUMN "AREA"."AREA_SIZE" IS '区域面积';
   COMMENT ON COLUMN "AREA"."CATEGORY" IS '区域类别（RETAIL, EVENT, OTHER等），用于区分不同类型的区域';
--------------------------------------------------------
--  DDL for Table CAR
--------------------------------------------------------

  CREATE TABLE "CAR" 
   (	"LICENSE_PLATE_NUMBER" VARCHAR2(20 BYTE), 
	"PARK_START" DATE, 
	"PARK_END" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "CAR"."LICENSE_PLATE_NUMBER" IS '车牌号';
   COMMENT ON COLUMN "CAR"."PARK_START" IS '停车起始时间';
   COMMENT ON COLUMN "CAR"."PARK_END" IS '停车结束时间';
--------------------------------------------------------
--  DDL for Table COLLABORATION
--------------------------------------------------------

  CREATE TABLE "COLLABORATION" 
   (	"COLLABORATION_ID" NUMBER(*,0), 
	"COLLABORATION_NAME" VARCHAR2(50 BYTE), 
	"CONTACTOR" VARCHAR2(50 BYTE), 
	"PHONE_NUMBER" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "COLLABORATION"."COLLABORATION_ID" IS '合作方ID';
   COMMENT ON COLUMN "COLLABORATION"."COLLABORATION_NAME" IS '合作方名称';
   COMMENT ON COLUMN "COLLABORATION"."CONTACTOR" IS '负责人';
   COMMENT ON COLUMN "COLLABORATION"."PHONE_NUMBER" IS '联系方式';
   COMMENT ON COLUMN "COLLABORATION"."EMAIL" IS '联系方式';
--------------------------------------------------------
--  DDL for Table EQUIPMENT
--------------------------------------------------------

  CREATE TABLE "EQUIPMENT" 
   (	"EQUIPMENT_ID" NUMBER(*,0), 
	"EQUIPMENT_TYPE" VARCHAR2(50 BYTE), 
	"EQUIPMENT_STATUS" VARCHAR2(20 BYTE) DEFAULT 0, 
	"PORT" VARCHAR2(50 BYTE), 
	"EQUIPMENT_COST" NUMBER(10,2), 
	"BUY_TIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "EQUIPMENT"."EQUIPMENT_ID" IS '设备ID';
   COMMENT ON COLUMN "EQUIPMENT"."EQUIPMENT_TYPE" IS '设备类型，如空调、摄像头';
   COMMENT ON COLUMN "EQUIPMENT"."EQUIPMENT_STATUS" IS '设备状态（正常/故障/维修中），编码表示';
   COMMENT ON COLUMN "EQUIPMENT"."PORT" IS '接口（如何接入设备）';
   COMMENT ON COLUMN "EQUIPMENT"."EQUIPMENT_COST" IS '设备花费';
   COMMENT ON COLUMN "EQUIPMENT"."BUY_TIME" IS '购买时间';
--------------------------------------------------------
--  DDL for Table EQUIPMENT_LOCATION
--------------------------------------------------------

  CREATE TABLE "EQUIPMENT_LOCATION" 
   (	"EQUIPMENT_ID" NUMBER(*,0), 
	"AREA_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "EQUIPMENT_LOCATION"."EQUIPMENT_ID" IS '设备ID';
   COMMENT ON COLUMN "EQUIPMENT_LOCATION"."AREA_ID" IS '区域ID';
--------------------------------------------------------
--  DDL for Table EVENT
--------------------------------------------------------

  CREATE TABLE "EVENT" 
   (	"EVENT_ID" NUMBER(*,0), 
	"EVENT_NAME" VARCHAR2(50 BYTE), 
	"EVENT_START" DATE, 
	"EVENT_END" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "EVENT"."EVENT_ID" IS '活动ID';
   COMMENT ON COLUMN "EVENT"."EVENT_NAME" IS '活动名';
   COMMENT ON COLUMN "EVENT"."EVENT_START" IS '活动开始时间';
   COMMENT ON COLUMN "EVENT"."EVENT_END" IS '活动结束时间';
--------------------------------------------------------
--  DDL for Table EVENT_AREA
--------------------------------------------------------

  CREATE TABLE "EVENT_AREA" 
   (	"AREA_ID" NUMBER(*,0), 
	"CAPACITY" NUMBER(*,0), 
	"AREA_FEE" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "EVENT_AREA"."AREA_ID" IS '区域ID';
   COMMENT ON COLUMN "EVENT_AREA"."CAPACITY" IS '容量';
   COMMENT ON COLUMN "EVENT_AREA"."AREA_FEE" IS '区域租金，单位：元/次';
--------------------------------------------------------
--  DDL for Table MONTH_SALARY_COST
--------------------------------------------------------

  CREATE TABLE "MONTH_SALARY_COST" 
   (	"MONTH_TIME" DATE, 
	"TOTAL_COST" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "MONTH_SALARY_COST"."MONTH_TIME" IS '月度时间';
   COMMENT ON COLUMN "MONTH_SALARY_COST"."TOTAL_COST" IS '当月工资总支出';
--------------------------------------------------------
--  DDL for Table OTHER_AREA
--------------------------------------------------------

  CREATE TABLE "OTHER_AREA" 
   (	"AREA_ID" NUMBER(*,0), 
	"TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "OTHER_AREA"."AREA_ID" IS '区域ID';
   COMMENT ON COLUMN "OTHER_AREA"."TYPE" IS '类别（卫生间、杂物间等）';
--------------------------------------------------------
--  DDL for Table PARK
--------------------------------------------------------

  CREATE TABLE "PARK" 
   (	"LICENSE_PLATE_NUMBER" VARCHAR2(20 BYTE), 
	"PARKING_SPACE_ID" NUMBER(*,0), 
	"PARK_START" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "PARK"."LICENSE_PLATE_NUMBER" IS '车牌号';
   COMMENT ON COLUMN "PARK"."PARKING_SPACE_ID" IS '车位ID';
   COMMENT ON COLUMN "PARK"."PARK_START" IS '停车开始时间';
--------------------------------------------------------
--  DDL for Table PARKING_LOT
--------------------------------------------------------

  CREATE TABLE "PARKING_LOT" 
   (	"AREA_ID" NUMBER(*,0), 
	"PARKING_FEE" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "PARKING_LOT"."AREA_ID" IS '区域ID';
   COMMENT ON COLUMN "PARKING_LOT"."PARKING_FEE" IS '停车费(元/小时)';
--------------------------------------------------------
--  DDL for Table PARKING_SPACE
--------------------------------------------------------

  CREATE TABLE "PARKING_SPACE" 
   (	"PARKING_SPACE_ID" NUMBER(*,0), 
	"OCCUPIED" NUMBER(*,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "PARKING_SPACE"."PARKING_SPACE_ID" IS '车位ID';
   COMMENT ON COLUMN "PARKING_SPACE"."OCCUPIED" IS '是否有车，0-否，1-是';
--------------------------------------------------------
--  DDL for Table PARKING_SPACE_DISTRIBUTION
--------------------------------------------------------

  CREATE TABLE "PARKING_SPACE_DISTRIBUTION" 
   (	"AREA_ID" NUMBER(*,0), 
	"PARKING_SPACE_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "PARKING_SPACE_DISTRIBUTION"."AREA_ID" IS '区域ID';
   COMMENT ON COLUMN "PARKING_SPACE_DISTRIBUTION"."PARKING_SPACE_ID" IS '车位ID';
--------------------------------------------------------
--  DDL for Table PART_STORE
--------------------------------------------------------

  CREATE TABLE "PART_STORE" 
   (	"EVENT_ID" NUMBER(*,0), 
	"STORE_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "PART_STORE"."EVENT_ID" IS '活动ID';
   COMMENT ON COLUMN "PART_STORE"."STORE_ID" IS '商店ID';
--------------------------------------------------------
--  DDL for Table RENT_STORE
--------------------------------------------------------

  CREATE TABLE "RENT_STORE" 
   (	"STORE_ID" NUMBER(*,0), 
	"AREA_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "RENT_STORE"."STORE_ID" IS '店铺ID';
   COMMENT ON COLUMN "RENT_STORE"."AREA_ID" IS '区域ID';
--------------------------------------------------------
--  DDL for Table REPAIR_ORDER
--------------------------------------------------------

  CREATE TABLE "REPAIR_ORDER" 
   (	"EQUIPMENT_ID" NUMBER(*,0), 
	"STAFF_ID" NUMBER(*,0), 
	"REPAIR_START" DATE, 
	"REPAIR_END" DATE, 
	"REPAIR_COST" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "REPAIR_ORDER"."EQUIPMENT_ID" IS '设备ID';
   COMMENT ON COLUMN "REPAIR_ORDER"."STAFF_ID" IS '员工ID';
   COMMENT ON COLUMN "REPAIR_ORDER"."REPAIR_START" IS '维修开始时间';
   COMMENT ON COLUMN "REPAIR_ORDER"."REPAIR_END" IS '维修结束时间';
   COMMENT ON COLUMN "REPAIR_ORDER"."REPAIR_COST" IS '维修花费';
--------------------------------------------------------
--  DDL for Table RETAIL_AREA
--------------------------------------------------------

  CREATE TABLE "RETAIL_AREA" 
   (	"AREA_ID" NUMBER(*,0), 
	"RENT_STATUS" VARCHAR2(20 BYTE), 
	"BASE_RENT" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "RETAIL_AREA"."AREA_ID" IS '区域ID';
   COMMENT ON COLUMN "RETAIL_AREA"."RENT_STATUS" IS '出租状态';
   COMMENT ON COLUMN "RETAIL_AREA"."BASE_RENT" IS '租金';
--------------------------------------------------------
--  DDL for Table SALARY_SLIP
--------------------------------------------------------

  CREATE TABLE "SALARY_SLIP" 
   (	"STAFF_ID" NUMBER(*,0), 
	"MONTH_TIME" DATE, 
	"ATD_COUNT" NUMBER(*,0), 
	"BONUS" NUMBER(10,2), 
	"FINE" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "SALARY_SLIP"."STAFF_ID" IS '员工ID';
   COMMENT ON COLUMN "SALARY_SLIP"."MONTH_TIME" IS '月度时间';
   COMMENT ON COLUMN "SALARY_SLIP"."ATD_COUNT" IS '考勤次数';
   COMMENT ON COLUMN "SALARY_SLIP"."BONUS" IS '奖金';
   COMMENT ON COLUMN "SALARY_SLIP"."FINE" IS '罚金';
--------------------------------------------------------
--  DDL for Table SALE_EVENT
--------------------------------------------------------

  CREATE TABLE "SALE_EVENT" 
   (	"EVENT_ID" NUMBER(*,0), 
	"COST" NUMBER(10,2), 
	"DESCRIPTION" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "SALE_EVENT"."EVENT_ID" IS '活动ID';
   COMMENT ON COLUMN "SALE_EVENT"."COST" IS '活动花费';
   COMMENT ON COLUMN "SALE_EVENT"."DESCRIPTION" IS '活动描述';
--------------------------------------------------------
--  DDL for Table STAFF
--------------------------------------------------------

  CREATE TABLE "STAFF" 
   (	"STAFF_ID" NUMBER(*,0), 
	"STAFF_NAME" VARCHAR2(50 BYTE), 
	"STAFF_SEX" VARCHAR2(10 BYTE), 
	"STAFF_APARTMENT" VARCHAR2(50 BYTE), 
	"STAFF_POSITION" VARCHAR2(50 BYTE), 
	"STAFF_SALARY" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "STAFF"."STAFF_ID" IS '员工ID';
   COMMENT ON COLUMN "STAFF"."STAFF_NAME" IS '员工名称';
   COMMENT ON COLUMN "STAFF"."STAFF_SEX" IS '员工性别';
   COMMENT ON COLUMN "STAFF"."STAFF_APARTMENT" IS '部门';
   COMMENT ON COLUMN "STAFF"."STAFF_POSITION" IS '员工职位';
   COMMENT ON COLUMN "STAFF"."STAFF_SALARY" IS '基础薪资';
--------------------------------------------------------
--  DDL for Table STAFF_ACCOUNT
--------------------------------------------------------

  CREATE TABLE "STAFF_ACCOUNT" 
   (	"ACCOUNT" VARCHAR2(50 BYTE), 
	"STAFF_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "STAFF_ACCOUNT"."ACCOUNT" IS '账号';
   COMMENT ON COLUMN "STAFF_ACCOUNT"."STAFF_ID" IS '员工ID';
--------------------------------------------------------
--  DDL for Table STORE
--------------------------------------------------------

  CREATE TABLE "STORE" 
   (	"STORE_ID" NUMBER(*,0), 
	"STORE_NAME" VARCHAR2(50 BYTE), 
	"STORE_STATUS" VARCHAR2(20 BYTE) DEFAULT 0, 
	"STORE_TYPE" VARCHAR2(20 BYTE), 
	"TENANT_NAME" VARCHAR2(20 BYTE), 
	"CONTACT_INFO" VARCHAR2(20 BYTE), 
	"RENT_START" DATE, 
	"RENT_END" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "STORE"."STORE_ID" IS '店铺ID';
   COMMENT ON COLUMN "STORE"."STORE_NAME" IS '店铺名';
   COMMENT ON COLUMN "STORE"."STORE_STATUS" IS '店铺状态，正常营业/打烊/歇业/翻新';
   COMMENT ON COLUMN "STORE"."STORE_TYPE" IS '店铺类型，个人/企业连锁';
   COMMENT ON COLUMN "STORE"."TENANT_NAME" IS '租户名';
   COMMENT ON COLUMN "STORE"."CONTACT_INFO" IS '租户联系方式';
   COMMENT ON COLUMN "STORE"."RENT_START" IS '租用起始时间';
   COMMENT ON COLUMN "STORE"."RENT_END" IS '租用结束时间';
--------------------------------------------------------
--  DDL for Table STORE_ACCOUNT
--------------------------------------------------------

  CREATE TABLE "STORE_ACCOUNT" 
   (	"ACCOUNT" VARCHAR2(50 BYTE), 
	"STORE_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "STORE_ACCOUNT"."ACCOUNT" IS '账号ID';
   COMMENT ON COLUMN "STORE_ACCOUNT"."STORE_ID" IS '店铺ID';
--------------------------------------------------------
--  DDL for Table TEMP_AUTHORITY
--------------------------------------------------------

  CREATE TABLE "TEMP_AUTHORITY" 
   (	"ACCOUNT" VARCHAR2(50 BYTE), 
	"EVENT_ID" NUMBER(*,0), 
	"TEMP_AUTHORITY" NUMBER(*,0), 
	"AUTHORITY_CONTENT" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TEMP_AUTHORITY"."ACCOUNT" IS '账号';
   COMMENT ON COLUMN "TEMP_AUTHORITY"."EVENT_ID" IS '活动ID';
   COMMENT ON COLUMN "TEMP_AUTHORITY"."TEMP_AUTHORITY" IS '活动临时权限';
   COMMENT ON COLUMN "TEMP_AUTHORITY"."AUTHORITY_CONTENT" IS '权限描述';
--------------------------------------------------------
--  DDL for Table VENUE_EVENT
--------------------------------------------------------

  CREATE TABLE "VENUE_EVENT" 
   (	"EVENT_ID" NUMBER(*,0), 
	"HEADCOUNT" NUMBER(*,0), 
	"FEE" NUMBER(10,2), 
	"CAPACITY" NUMBER(*,0), 
	"EXPENSE" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "VENUE_EVENT"."EVENT_ID" IS '活动ID';
   COMMENT ON COLUMN "VENUE_EVENT"."HEADCOUNT" IS '参与人数';
   COMMENT ON COLUMN "VENUE_EVENT"."FEE" IS '活动收费，单位：元/人';
   COMMENT ON COLUMN "VENUE_EVENT"."CAPACITY" IS '活动容量';
   COMMENT ON COLUMN "VENUE_EVENT"."EXPENSE" IS '活动花费，单位：元';
--------------------------------------------------------
--  DDL for Table VENUE_EVENT_DETAIL
--------------------------------------------------------

  CREATE TABLE "VENUE_EVENT_DETAIL" 
   (	"EVENT_ID" NUMBER(*,0), 
	"AREA_ID" NUMBER(*,0), 
	"COLLABORATION_ID" NUMBER(*,0), 
	"RENT_START" DATE, 
	"RENT_END" DATE, 
	"STATUS" VARCHAR2(20 BYTE), 
	"FUNDING" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "VENUE_EVENT_DETAIL"."EVENT_ID" IS '活动ID';
   COMMENT ON COLUMN "VENUE_EVENT_DETAIL"."AREA_ID" IS '区域ID';
   COMMENT ON COLUMN "VENUE_EVENT_DETAIL"."COLLABORATION_ID" IS '合作方ID';
   COMMENT ON COLUMN "VENUE_EVENT_DETAIL"."RENT_START" IS '租用起始时间';
   COMMENT ON COLUMN "VENUE_EVENT_DETAIL"."RENT_END" IS '租用结束时间';
   COMMENT ON COLUMN "VENUE_EVENT_DETAIL"."STATUS" IS '场地状态';
   COMMENT ON COLUMN "VENUE_EVENT_DETAIL"."FUNDING" IS '投资金额';
--------------------------------------------------------
--  DDL for Index ACCOUNT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ACCOUNT_PK" ON "ACCOUNT" ("ACCOUNT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CAR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAR_PK" ON "CAR" ("LICENSE_PLATE_NUMBER", "PARK_START") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TEMP_AUTHORITY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEMP_AUTHORITY_PK" ON "TEMP_AUTHORITY" ("ACCOUNT", "EVENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EVENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EVENT_PK" ON "EVENT" ("EVENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STORE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STORE_PK" ON "STORE" ("STORE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AREA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AREA_PK" ON "AREA" ("AREA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MONTH_SALARY_COST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MONTH_SALARY_COST_PK" ON "MONTH_SALARY_COST" ("MONTH_TIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RENT_STORE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RENT_STORE_PK" ON "RENT_STORE" ("STORE_ID", "AREA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SALE_EVENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SALE_EVENT_PK" ON "SALE_EVENT" ("EVENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STORE_ACCOUNT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STORE_ACCOUNT_PK" ON "STORE_ACCOUNT" ("ACCOUNT", "STORE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EQUIPMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EQUIPMENT_PK" ON "EQUIPMENT" ("EQUIPMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PAY_SLIP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PAY_SLIP_PK" ON "SALARY_SLIP" ("STAFF_ID", "MONTH_TIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RETAIL_UNIT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RETAIL_UNIT_PK" ON "RETAIL_AREA" ("AREA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VEMUE_EVENT_DETAIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VEMUE_EVENT_DETAIL_PK" ON "VENUE_EVENT_DETAIL" ("EVENT_ID", "AREA_ID", "COLLABORATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PART_STORE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PART_STORE_PK" ON "PART_STORE" ("EVENT_ID", "STORE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COLLABORATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "COLLABORATION_PK" ON "COLLABORATION" ("COLLABORATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PARKING_SPACE_DISTRIBUTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PARKING_SPACE_DISTRIBUTION_PK" ON "PARKING_SPACE_DISTRIBUTION" ("AREA_ID", "PARKING_SPACE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PARK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PARK_PK" ON "PARK" ("LICENSE_PLATE_NUMBER", "PARKING_SPACE_ID", "PARK_START") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EVENT_AREA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EVENT_AREA_PK" ON "EVENT_AREA" ("AREA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REPAIR_ORDER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REPAIR_ORDER_PK" ON "REPAIR_ORDER" ("EQUIPMENT_ID", "STAFF_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STAFF_ACCOUNT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STAFF_ACCOUNT_PK" ON "STAFF_ACCOUNT" ("ACCOUNT", "STAFF_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OTHER_AREA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OTHER_AREA_PK" ON "OTHER_AREA" ("AREA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PARKING_SPACE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PARKING_SPACE_PK" ON "PARKING_SPACE" ("PARKING_SPACE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STAFF_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STAFF_PK" ON "STAFF" ("STAFF_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PARKING_LOT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PARKING_LOT_PK" ON "PARKING_LOT" ("AREA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VENUE_EVENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENUE_EVENT_PK" ON "VENUE_EVENT" ("EVENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EQUIPMENT_LOCATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EQUIPMENT_LOCATION_PK" ON "EQUIPMENT_LOCATION" ("EQUIPMENT_ID", "AREA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger COLLABORATION_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "COLLABORATION_ID_TRG" 
    BEFORE INSERT ON COLLABORATION
    FOR EACH ROW
BEGIN
    IF :NEW.COLLABORATION_ID IS NULL THEN
        SELECT COLLABORATION_ID_SEQ.NEXTVAL INTO :NEW.COLLABORATION_ID FROM DUAL;
    END IF;
END;
/
ALTER TRIGGER "COLLABORATION_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EVENT_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "EVENT_ID_TRG" 
    BEFORE INSERT ON EVENT
    FOR EACH ROW
BEGIN
    IF :NEW.EVENT_ID IS NULL THEN
        SELECT EVENT_ID_SEQ.NEXTVAL INTO :NEW.EVENT_ID FROM DUAL;
    END IF;
END;
/
ALTER TRIGGER "EVENT_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger STAFF_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "STAFF_ID_TRG" 
    BEFORE INSERT ON STAFF
    FOR EACH ROW
BEGIN
    IF :NEW.STAFF_ID IS NULL THEN
        SELECT STAFF_ID_SEQ.NEXTVAL INTO :NEW.STAFF_ID FROM DUAL;
    END IF;
END;
/
ALTER TRIGGER "STAFF_ID_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table STAFF
--------------------------------------------------------

  ALTER TABLE "STAFF" ADD CONSTRAINT "STAFF_PK" PRIMARY KEY ("STAFF_ID")
  USING INDEX "STAFF_PK"  ENABLE;
  ALTER TABLE "STAFF" MODIFY ("STAFF_ID" NOT NULL ENABLE);
  ALTER TABLE "STAFF" MODIFY ("STAFF_NAME" NOT NULL ENABLE);
  ALTER TABLE "STAFF" MODIFY ("STAFF_APARTMENT" NOT NULL ENABLE);
  ALTER TABLE "STAFF" MODIFY ("STAFF_POSITION" NOT NULL ENABLE);
  ALTER TABLE "STAFF" MODIFY ("STAFF_SALARY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VENUE_EVENT_DETAIL
--------------------------------------------------------

  ALTER TABLE "VENUE_EVENT_DETAIL" ADD CONSTRAINT "VEMUE_EVENT_DETAIL_PK" PRIMARY KEY ("EVENT_ID", "AREA_ID", "COLLABORATION_ID")
  USING INDEX "VEMUE_EVENT_DETAIL_PK"  ENABLE;
  ALTER TABLE "VENUE_EVENT_DETAIL" MODIFY ("EVENT_ID" NOT NULL ENABLE);
  ALTER TABLE "VENUE_EVENT_DETAIL" MODIFY ("AREA_ID" NOT NULL ENABLE);
  ALTER TABLE "VENUE_EVENT_DETAIL" MODIFY ("COLLABORATION_ID" NOT NULL ENABLE);
  ALTER TABLE "VENUE_EVENT_DETAIL" MODIFY ("RENT_START" NOT NULL ENABLE);
  ALTER TABLE "VENUE_EVENT_DETAIL" MODIFY ("RENT_END" NOT NULL ENABLE);
  ALTER TABLE "VENUE_EVENT_DETAIL" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "VENUE_EVENT_DETAIL" MODIFY ("FUNDING" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PART_STORE
--------------------------------------------------------

  ALTER TABLE "PART_STORE" ADD CONSTRAINT "PART_STORE_PK" PRIMARY KEY ("EVENT_ID", "STORE_ID")
  USING INDEX "PART_STORE_PK"  ENABLE;
  ALTER TABLE "PART_STORE" MODIFY ("EVENT_ID" NOT NULL ENABLE);
  ALTER TABLE "PART_STORE" MODIFY ("STORE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COLLABORATION
--------------------------------------------------------

  ALTER TABLE "COLLABORATION" MODIFY ("COLLABORATION_ID" NOT NULL ENABLE);
  ALTER TABLE "COLLABORATION" MODIFY ("COLLABORATION_NAME" NOT NULL ENABLE);
  ALTER TABLE "COLLABORATION" ADD CONSTRAINT "COLLABORATION_PK" PRIMARY KEY ("COLLABORATION_ID")
  USING INDEX "COLLABORATION_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EVENT
--------------------------------------------------------

  ALTER TABLE "EVENT" MODIFY ("EVENT_ID" NOT NULL ENABLE);
  ALTER TABLE "EVENT" MODIFY ("EVENT_NAME" NOT NULL ENABLE);
  ALTER TABLE "EVENT" MODIFY ("EVENT_START" NOT NULL ENABLE);
  ALTER TABLE "EVENT" ADD CONSTRAINT "EVENT_PK" PRIMARY KEY ("EVENT_ID")
  USING INDEX "EVENT_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PARKING_SPACE_DISTRIBUTION
--------------------------------------------------------

  ALTER TABLE "PARKING_SPACE_DISTRIBUTION" MODIFY ("AREA_ID" NOT NULL ENABLE);
  ALTER TABLE "PARKING_SPACE_DISTRIBUTION" MODIFY ("PARKING_SPACE_ID" NOT NULL ENABLE);
  ALTER TABLE "PARKING_SPACE_DISTRIBUTION" ADD CONSTRAINT "PARKING_SPACE_DISTRIBUTION_PK" PRIMARY KEY ("AREA_ID", "PARKING_SPACE_ID")
  USING INDEX "PARKING_SPACE_DISTRIBUTION_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AREA
--------------------------------------------------------

  ALTER TABLE "AREA" ADD CONSTRAINT "CHK_AREA_CATEGORY" CHECK (CATEGORY IN ('RETAIL', 'EVENT', 'PARKING', 'OTHER')) ENABLE;
  ALTER TABLE "AREA" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "AREA" ADD CONSTRAINT "AREA_PK" PRIMARY KEY ("AREA_ID")
  USING INDEX "AREA_PK"  ENABLE;
  ALTER TABLE "AREA" MODIFY ("AREA_ID" NOT NULL ENABLE);
  ALTER TABLE "AREA" MODIFY ("ISEMPTY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RETAIL_AREA
--------------------------------------------------------

  ALTER TABLE "RETAIL_AREA" ADD CONSTRAINT "RETAIL_UNIT_PK" PRIMARY KEY ("AREA_ID")
  USING INDEX "RETAIL_UNIT_PK"  ENABLE;
  ALTER TABLE "RETAIL_AREA" MODIFY ("AREA_ID" NOT NULL ENABLE);
  ALTER TABLE "RETAIL_AREA" MODIFY ("RENT_STATUS" NOT NULL ENABLE);
  ALTER TABLE "RETAIL_AREA" MODIFY ("BASE_RENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REPAIR_ORDER
--------------------------------------------------------

  ALTER TABLE "REPAIR_ORDER" ADD CONSTRAINT "REPAIR_ORDER_PK" PRIMARY KEY ("EQUIPMENT_ID", "STAFF_ID")
  USING INDEX "REPAIR_ORDER_PK"  ENABLE;
  ALTER TABLE "REPAIR_ORDER" MODIFY ("EQUIPMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "REPAIR_ORDER" MODIFY ("STAFF_ID" NOT NULL ENABLE);
  ALTER TABLE "REPAIR_ORDER" MODIFY ("REPAIR_START" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SALE_EVENT
--------------------------------------------------------

  ALTER TABLE "SALE_EVENT" ADD CONSTRAINT "SALE_EVENT_PK" PRIMARY KEY ("EVENT_ID")
  USING INDEX "SALE_EVENT_PK"  ENABLE;
  ALTER TABLE "SALE_EVENT" MODIFY ("EVENT_ID" NOT NULL ENABLE);
  ALTER TABLE "SALE_EVENT" MODIFY ("COST" NOT NULL ENABLE);
  ALTER TABLE "SALE_EVENT" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PARK
--------------------------------------------------------

  ALTER TABLE "PARK" MODIFY ("LICENSE_PLATE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "PARK" MODIFY ("PARKING_SPACE_ID" NOT NULL ENABLE);
  ALTER TABLE "PARK" MODIFY ("PARK_START" NOT NULL ENABLE);
  ALTER TABLE "PARK" ADD CONSTRAINT "PARK_PK" PRIMARY KEY ("LICENSE_PLATE_NUMBER", "PARKING_SPACE_ID", "PARK_START")
  USING INDEX "PARK_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STAFF_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "STAFF_ACCOUNT" ADD CONSTRAINT "STAFF_ACCOUNT_PK" PRIMARY KEY ("ACCOUNT", "STAFF_ID")
  USING INDEX "STAFF_ACCOUNT_PK"  ENABLE;
  ALTER TABLE "STAFF_ACCOUNT" MODIFY ("ACCOUNT" NOT NULL ENABLE);
  ALTER TABLE "STAFF_ACCOUNT" MODIFY ("STAFF_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PARKING_SPACE
--------------------------------------------------------

  ALTER TABLE "PARKING_SPACE" ADD CONSTRAINT "PARKING_SPACE_PK" PRIMARY KEY ("PARKING_SPACE_ID")
  USING INDEX "PARKING_SPACE_PK"  ENABLE;
  ALTER TABLE "PARKING_SPACE" MODIFY ("PARKING_SPACE_ID" NOT NULL ENABLE);
  ALTER TABLE "PARKING_SPACE" MODIFY ("OCCUPIED" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EQUIPMENT
--------------------------------------------------------

  ALTER TABLE "EQUIPMENT" MODIFY ("EQUIPMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "EQUIPMENT" MODIFY ("EQUIPMENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "EQUIPMENT" MODIFY ("EQUIPMENT_STATUS" NOT NULL ENABLE);
  ALTER TABLE "EQUIPMENT" MODIFY ("BUY_TIME" NOT NULL ENABLE);
  ALTER TABLE "EQUIPMENT" ADD CONSTRAINT "EQUIPMENT_PK" PRIMARY KEY ("EQUIPMENT_ID")
  USING INDEX "EQUIPMENT_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SALARY_SLIP
--------------------------------------------------------

  ALTER TABLE "SALARY_SLIP" ADD CONSTRAINT "PAY_SLIP_PK" PRIMARY KEY ("STAFF_ID", "MONTH_TIME")
  USING INDEX "PAY_SLIP_PK"  ENABLE;
  ALTER TABLE "SALARY_SLIP" MODIFY ("STAFF_ID" NOT NULL ENABLE);
  ALTER TABLE "SALARY_SLIP" MODIFY ("MONTH_TIME" NOT NULL ENABLE);
  ALTER TABLE "SALARY_SLIP" MODIFY ("ATD_COUNT" NOT NULL ENABLE);
  ALTER TABLE "SALARY_SLIP" MODIFY ("BONUS" NOT NULL ENABLE);
  ALTER TABLE "SALARY_SLIP" MODIFY ("FINE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TEMP_AUTHORITY
--------------------------------------------------------

  ALTER TABLE "TEMP_AUTHORITY" ADD CONSTRAINT "TEMP_AUTHORITY_PK" PRIMARY KEY ("ACCOUNT", "EVENT_ID")
  USING INDEX "TEMP_AUTHORITY_PK"  ENABLE;
  ALTER TABLE "TEMP_AUTHORITY" MODIFY ("ACCOUNT" NOT NULL ENABLE);
  ALTER TABLE "TEMP_AUTHORITY" MODIFY ("EVENT_ID" NOT NULL ENABLE);
  ALTER TABLE "TEMP_AUTHORITY" MODIFY ("TEMP_AUTHORITY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CAR
--------------------------------------------------------

  ALTER TABLE "CAR" ADD CONSTRAINT "CAR_PK" PRIMARY KEY ("LICENSE_PLATE_NUMBER", "PARK_START")
  USING INDEX "CAR_PK"  ENABLE;
  ALTER TABLE "CAR" MODIFY ("LICENSE_PLATE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "CAR" MODIFY ("PARK_START" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MONTH_SALARY_COST
--------------------------------------------------------

  ALTER TABLE "MONTH_SALARY_COST" MODIFY ("MONTH_TIME" NOT NULL ENABLE);
  ALTER TABLE "MONTH_SALARY_COST" MODIFY ("TOTAL_COST" NOT NULL ENABLE);
  ALTER TABLE "MONTH_SALARY_COST" ADD CONSTRAINT "MONTH_SALARY_COST_PK" PRIMARY KEY ("MONTH_TIME")
  USING INDEX "MONTH_SALARY_COST_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EQUIPMENT_LOCATION
--------------------------------------------------------

  ALTER TABLE "EQUIPMENT_LOCATION" MODIFY ("EQUIPMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "EQUIPMENT_LOCATION" MODIFY ("AREA_ID" NOT NULL ENABLE);
  ALTER TABLE "EQUIPMENT_LOCATION" ADD CONSTRAINT "EQUIPMENT_LOCATION_PK" PRIMARY KEY ("EQUIPMENT_ID", "AREA_ID")
  USING INDEX "EQUIPMENT_LOCATION_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PARKING_LOT
--------------------------------------------------------

  ALTER TABLE "PARKING_LOT" MODIFY ("AREA_ID" NOT NULL ENABLE);
  ALTER TABLE "PARKING_LOT" MODIFY ("PARKING_FEE" NOT NULL ENABLE);
  ALTER TABLE "PARKING_LOT" ADD CONSTRAINT "PARKING_LOT_PK" PRIMARY KEY ("AREA_ID")
  USING INDEX "PARKING_LOT_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RENT_STORE
--------------------------------------------------------

  ALTER TABLE "RENT_STORE" ADD CONSTRAINT "RENT_STORE_PK" PRIMARY KEY ("STORE_ID", "AREA_ID")
  USING INDEX "RENT_STORE_PK"  ENABLE;
  ALTER TABLE "RENT_STORE" MODIFY ("STORE_ID" NOT NULL ENABLE);
  ALTER TABLE "RENT_STORE" MODIFY ("AREA_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STORE
--------------------------------------------------------

  ALTER TABLE "STORE" ADD CONSTRAINT "STORE_PK" PRIMARY KEY ("STORE_ID")
  USING INDEX "STORE_PK"  ENABLE;
  ALTER TABLE "STORE" MODIFY ("STORE_ID" NOT NULL ENABLE);
  ALTER TABLE "STORE" MODIFY ("STORE_NAME" NOT NULL ENABLE);
  ALTER TABLE "STORE" MODIFY ("STORE_STATUS" NOT NULL ENABLE);
  ALTER TABLE "STORE" MODIFY ("STORE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "STORE" MODIFY ("TENANT_NAME" NOT NULL ENABLE);
  ALTER TABLE "STORE" MODIFY ("CONTACT_INFO" NOT NULL ENABLE);
  ALTER TABLE "STORE" MODIFY ("RENT_START" NOT NULL ENABLE);
  ALTER TABLE "STORE" MODIFY ("RENT_END" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OTHER_AREA
--------------------------------------------------------

  ALTER TABLE "OTHER_AREA" MODIFY ("AREA_ID" NOT NULL ENABLE);
  ALTER TABLE "OTHER_AREA" ADD CONSTRAINT "OTHER_AREA_PK" PRIMARY KEY ("AREA_ID")
  USING INDEX "OTHER_AREA_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STORE_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "STORE_ACCOUNT" ADD CONSTRAINT "STORE_ACCOUNT_PK" PRIMARY KEY ("ACCOUNT", "STORE_ID")
  USING INDEX "STORE_ACCOUNT_PK"  ENABLE;
  ALTER TABLE "STORE_ACCOUNT" MODIFY ("ACCOUNT" NOT NULL ENABLE);
  ALTER TABLE "STORE_ACCOUNT" MODIFY ("STORE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ACCOUNT
--------------------------------------------------------

  ALTER TABLE "ACCOUNT" MODIFY ("ACCOUNT" NOT NULL ENABLE);
  ALTER TABLE "ACCOUNT" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "ACCOUNT" MODIFY ("IDENTITY" NOT NULL ENABLE);
  ALTER TABLE "ACCOUNT" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "ACCOUNT" MODIFY ("AUTHORITY" NOT NULL ENABLE);
  ALTER TABLE "ACCOUNT" ADD CONSTRAINT "ACCOUNT_PK" PRIMARY KEY ("ACCOUNT")
  USING INDEX "ACCOUNT_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EVENT_AREA
--------------------------------------------------------

  ALTER TABLE "EVENT_AREA" MODIFY ("AREA_ID" NOT NULL ENABLE);
  ALTER TABLE "EVENT_AREA" MODIFY ("AREA_FEE" NOT NULL ENABLE);
  ALTER TABLE "EVENT_AREA" ADD CONSTRAINT "EVENT_AREA_PK" PRIMARY KEY ("AREA_ID")
  USING INDEX "EVENT_AREA_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VENUE_EVENT
--------------------------------------------------------

  ALTER TABLE "VENUE_EVENT" ADD CONSTRAINT "VENUE_EVENT_PK" PRIMARY KEY ("EVENT_ID")
  USING INDEX "VENUE_EVENT_PK"  ENABLE;
  ALTER TABLE "VENUE_EVENT" MODIFY ("EVENT_ID" NOT NULL ENABLE);
  ALTER TABLE "VENUE_EVENT" MODIFY ("FEE" NOT NULL ENABLE);
  ALTER TABLE "VENUE_EVENT" MODIFY ("CAPACITY" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table EQUIPMENT_LOCATION
--------------------------------------------------------

  ALTER TABLE "EQUIPMENT_LOCATION" ADD CONSTRAINT "EQUIPMENT_LOCATION_FK1" FOREIGN KEY ("EQUIPMENT_ID")
	  REFERENCES "EQUIPMENT" ("EQUIPMENT_ID") ENABLE;
  ALTER TABLE "EQUIPMENT_LOCATION" ADD CONSTRAINT "EQUIPMENT_LOCATION_FK2" FOREIGN KEY ("AREA_ID")
	  REFERENCES "AREA" ("AREA_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EVENT_AREA
--------------------------------------------------------

  ALTER TABLE "EVENT_AREA" ADD CONSTRAINT "EVENT_AREA_FK1" FOREIGN KEY ("AREA_ID")
	  REFERENCES "AREA" ("AREA_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OTHER_AREA
--------------------------------------------------------

  ALTER TABLE "OTHER_AREA" ADD CONSTRAINT "OTHER_AREA_FK1" FOREIGN KEY ("AREA_ID")
	  REFERENCES "AREA" ("AREA_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PARK
--------------------------------------------------------

  ALTER TABLE "PARK" ADD CONSTRAINT "PARK_FK2" FOREIGN KEY ("LICENSE_PLATE_NUMBER", "PARK_START")
	  REFERENCES "CAR" ("LICENSE_PLATE_NUMBER", "PARK_START") ENABLE;
  ALTER TABLE "PARK" ADD CONSTRAINT "PARK_FK1" FOREIGN KEY ("PARKING_SPACE_ID")
	  REFERENCES "PARKING_SPACE" ("PARKING_SPACE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PARKING_LOT
--------------------------------------------------------

  ALTER TABLE "PARKING_LOT" ADD CONSTRAINT "PARKING_LOT_FK1" FOREIGN KEY ("AREA_ID")
	  REFERENCES "AREA" ("AREA_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PARKING_SPACE_DISTRIBUTION
--------------------------------------------------------

  ALTER TABLE "PARKING_SPACE_DISTRIBUTION" ADD CONSTRAINT "PARKING_SPACE_DISTRIBUTION_FK2" FOREIGN KEY ("AREA_ID")
	  REFERENCES "PARKING_LOT" ("AREA_ID") ENABLE;
  ALTER TABLE "PARKING_SPACE_DISTRIBUTION" ADD CONSTRAINT "PARKING_SPACE_DISTRIBUTION_FK1" FOREIGN KEY ("PARKING_SPACE_ID")
	  REFERENCES "PARKING_SPACE" ("PARKING_SPACE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PART_STORE
--------------------------------------------------------

  ALTER TABLE "PART_STORE" ADD CONSTRAINT "PART_STORE_FK1" FOREIGN KEY ("STORE_ID")
	  REFERENCES "STORE" ("STORE_ID") ENABLE;
  ALTER TABLE "PART_STORE" ADD CONSTRAINT "PART_STORE_FK2" FOREIGN KEY ("EVENT_ID")
	  REFERENCES "SALE_EVENT" ("EVENT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RENT_STORE
--------------------------------------------------------

  ALTER TABLE "RENT_STORE" ADD CONSTRAINT "RENT_STORE_FK1" FOREIGN KEY ("STORE_ID")
	  REFERENCES "STORE" ("STORE_ID") ENABLE;
  ALTER TABLE "RENT_STORE" ADD CONSTRAINT "RENT_STORE_FK2" FOREIGN KEY ("AREA_ID")
	  REFERENCES "RETAIL_AREA" ("AREA_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPAIR_ORDER
--------------------------------------------------------

  ALTER TABLE "REPAIR_ORDER" ADD CONSTRAINT "REPAIR_ORDER_FK1" FOREIGN KEY ("STAFF_ID")
	  REFERENCES "STAFF" ("STAFF_ID") ENABLE;
  ALTER TABLE "REPAIR_ORDER" ADD CONSTRAINT "REPAIR_ORDER_FK2" FOREIGN KEY ("EQUIPMENT_ID")
	  REFERENCES "EQUIPMENT" ("EQUIPMENT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RETAIL_AREA
--------------------------------------------------------

  ALTER TABLE "RETAIL_AREA" ADD CONSTRAINT "RETAIL_AREA_FK1" FOREIGN KEY ("AREA_ID")
	  REFERENCES "AREA" ("AREA_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SALARY_SLIP
--------------------------------------------------------

  ALTER TABLE "SALARY_SLIP" ADD CONSTRAINT "SALARY_SLIP_FK1" FOREIGN KEY ("STAFF_ID")
	  REFERENCES "STAFF" ("STAFF_ID") ENABLE;
  ALTER TABLE "SALARY_SLIP" ADD CONSTRAINT "SALARY_SLIP_FK2" FOREIGN KEY ("MONTH_TIME")
	  REFERENCES "MONTH_SALARY_COST" ("MONTH_TIME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SALE_EVENT
--------------------------------------------------------

  ALTER TABLE "SALE_EVENT" ADD CONSTRAINT "SALE_EVENT_FK1" FOREIGN KEY ("EVENT_ID")
	  REFERENCES "EVENT" ("EVENT_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STAFF_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "STAFF_ACCOUNT" ADD CONSTRAINT "STAFF_ACCOUNT_FK1" FOREIGN KEY ("ACCOUNT")
	  REFERENCES "ACCOUNT" ("ACCOUNT") ENABLE;
  ALTER TABLE "STAFF_ACCOUNT" ADD CONSTRAINT "STAFF_ACCOUNT_FK2" FOREIGN KEY ("STAFF_ID")
	  REFERENCES "STAFF" ("STAFF_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STORE_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "STORE_ACCOUNT" ADD CONSTRAINT "STORE_ACCOUNT_FK1" FOREIGN KEY ("ACCOUNT")
	  REFERENCES "ACCOUNT" ("ACCOUNT") ENABLE;
  ALTER TABLE "STORE_ACCOUNT" ADD CONSTRAINT "STORE_ACCOUNT_FK2" FOREIGN KEY ("STORE_ID")
	  REFERENCES "STORE" ("STORE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TEMP_AUTHORITY
--------------------------------------------------------

  ALTER TABLE "TEMP_AUTHORITY" ADD CONSTRAINT "TEMP_AUTHORITY_FK1" FOREIGN KEY ("ACCOUNT")
	  REFERENCES "ACCOUNT" ("ACCOUNT") ENABLE;
  ALTER TABLE "TEMP_AUTHORITY" ADD CONSTRAINT "TEMP_AUTHORITY_FK2" FOREIGN KEY ("EVENT_ID")
	  REFERENCES "VENUE_EVENT" ("EVENT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VENUE_EVENT
--------------------------------------------------------

  ALTER TABLE "VENUE_EVENT" ADD CONSTRAINT "VENUE_EVENT_FK1" FOREIGN KEY ("EVENT_ID")
	  REFERENCES "EVENT" ("EVENT_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VENUE_EVENT_DETAIL
--------------------------------------------------------

  ALTER TABLE "VENUE_EVENT_DETAIL" ADD CONSTRAINT "VEMUE_EVENT_DETAIL_FK3" FOREIGN KEY ("AREA_ID")
	  REFERENCES "EVENT_AREA" ("AREA_ID") ENABLE;
  ALTER TABLE "VENUE_EVENT_DETAIL" ADD CONSTRAINT "VEMUE_EVENT_DETAIL_FK2" FOREIGN KEY ("COLLABORATION_ID")
	  REFERENCES "COLLABORATION" ("COLLABORATION_ID") ENABLE;
  ALTER TABLE "VENUE_EVENT_DETAIL" ADD CONSTRAINT "VEMUE_EVENT_DETAIL_FK1" FOREIGN KEY ("EVENT_ID")
	  REFERENCES "VENUE_EVENT" ("EVENT_ID") ENABLE;
